name: CI
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install packages
        run: sudo apt install texlive texlive-xetex latexmk fonts-croscore -y && npm i -g pdf-to-svg
      - name: Generate files
        run: ./scripts/generate
      - name: Copy output files
        run: |
          rm -rf out
          mkdir -p out
          cp {generated,out}/resume.tex
          cp {generated,out}/resume.pdf
          cp {generated,out}/resume.svg
      - name: Update files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated files as of ${{ github.sha }}
          file_pattern: out
          commit_user_name: dtinth-bot
          commit_user_email: dtinth-bot@users.noreply.github.com
          commit_author: dtinth-bot <dtinth-bot@users.noreply.github.com>
